#!/bin/sh /etc/rc.common

START=90
STOP=10

USE_PROCD=1

start_service() {
    procd_open_instance "bluetooth_spp_service"
    procd_set_param command /bin/sh /usr/bin/bluetooth_spp_manager.sh
    procd_set_param respawn 3600 5 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    hciconfig hci0 down 2>/dev/null || true
}
