#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /bin/sh /usr/bin/obdclaw_uhttpd_watchdog.sh
    procd_set_param respawn 3600 5 5
    procd_close_instance
}
