#!/bin/sh /etc/rc.common

START=95
STOP=10

USE_PROCD=1

start_service() {
    procd_open_instance "rfcomm_a30m"
    procd_set_param command /bin/sh /usr/bin/rfcomm_a30m_bind.sh
    procd_set_param respawn 3600 5 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    rfcomm release 0 2>/dev/null || true
}
