#!/bin/sh /etc/rc.common

START=98
STOP=10
USE_PROCD=1

start_service() {
    procd_open_instance 'sta_dhcp_recover'
    procd_set_param command /bin/sh /usr/bin/sta_dhcp_recover.sh
    procd_set_param respawn 0 0 0
    procd_close_instance
}
