#!/bin/sh /etc/rc.common

START=98
STOP=10

start() {
    # This is deliberately a one-shot boot observation.  Restarting it would
    # repeatedly interfere with a DHCP exchange that is still settling.
    /bin/sh /usr/bin/sta_dhcp_recover.sh >/dev/null 2>&1 &
}
